services:
  #mysql service for the database
  mysql:
    image: mysql
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysqlROOT
      MYSQL_DATABASE: helfy_db
      command: --server-id=1 --log-bin=mysql-bin --binlog-format=ROW --gtid-mode=ON --enforce-gtid-consistency=ON
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
  #zookeeper for kafka
  zookeeper:
    image: debezium/zookeeper:2.7.3.Final
    ports:
      - "2181:2181"
  #kafka service for message brokering
  kafka:
    image: debezium/kafka:2.7.3.Final
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  #debezium service for change data capture
  debezium:
    image: debezium/connect:2.7.3.Final
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - kafka
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: helfy-connect-config
      OFFSET_STORAGE_TOPIC: helfy-connect-offsets
      STATUS_STORAGE_TOPIC: helfy-connects-statuses

  #build backend service from Dockerfile
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: mysqlROOT
      DB_NAME: helfy_db
  #build consumer service from Dockerfile
  consumer:
    build: ./consumer
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: helfy_db.helfy_table
#configure volume for data persistence of mysql
volumes:
  mysql_data:
    driver: local